version: 2.1
jobs:
  install-requirements:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys: 
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run: 
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies{{ checksum "requirements.txt" }}

  run-lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys: 
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: activate environment
          command: |
            ls -la
            . venv/bin/activate
      - run: 
          name: run lint
          command: |
            make lint
  
  run-tests:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys: 
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: activate environment
          command: |
            ls -la
            . venv/bin/activate
      - run: 
          name: run tests
          command: |
            make test

workflows:
  default:
    jobs:
      - install-requirements
      - run-lint:
          requires: [install-requirements]
      # - run-tests:
      #     requires: [install-requirements]
