version: 2.1
jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys: 
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run: 
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run: 
          name: run lint
          command: |
            . venv/bin/activate
            make lint
      - run: 
          name: run tests
          command: |
            . venv/bin/activate
            make test
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies{{ checksum "requirements.txt" }}
workflows:
  default:
    jobs:
      - build